apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: django-app
data:
  DB_HOST: "postgres-service"
  DB_USERNAME: "sampleuser"
  DB_PASSWORD: "sampleuser123"
  DB_NAME: "django-app"
  DB_PORT: "5432"
  STATIC_ROOT: "/data/static"

